### ISSUE TITLE
Blur Image reversed 

### ISSUE THREAD

**Issue by buihuuloc** [mob-sakai/UIEffect#156]
Hi there,

I got the problem that the blurred image was reversed by somehow.

It only happens on both devices and editor

Is there anyone got this problem?

**Comment by buihuuloc** [comment]
Also, 
Somehow the UISoftMask is also reversed

**Comment by buihuuloc** [comment]
@mob-sakai 
Have you ever seen this bug before?

It only happens in a specific condition.

**Comment by mob-sakai** [comment]
Hi @buihuuloc 

Yes.
In fact, this problem has occurred many times and has been fixed many times.
In most cases, this is due to changes in shaders and algorithms.
It is difficult to test on all platforms, devices, Unity versions and RenderModes...
I have no idea how to test this problem automatically.

>Somehow the UISoftMask is also reversed

 Does the problem occur with v0.7.2 released yesterday?

**Comment by mob-sakai** [comment]
>It only happens in a specific condition

Please tell me the detail.

**Comment by buihuuloc** [comment]
The SoftMask flip was fixed with the latest version.

**Comment by buihuuloc** [comment]
However, It still happens with UIEffect.
It still works on the editor. On the device, It only shows the black image

Unity Version: 18.3.1f1
UIEffect latest version:
Devices: iPhone 7+
<img width="481" alt="UIEffect_Catpure" src="https://user-images.githubusercontent.com/1252560/54485574-c26d5d00-48ad-11e9-8622-0245b91b09d7.png">
<img width="525" alt="Graphic Settings" src="https://user-images.githubusercontent.com/1252560/54485579-dd3fd180-48ad-11e9-9f1d-d43aba5e1fba.png">

**Comment by mob-sakai** [comment]
Thank you for the detail informations!

**Comment by mob-sakai** [comment]
Is RenderMode "Screen Space-Overlay"? Or "Screen Space-Camera"?

**Comment by buihuuloc** [comment]
I am using Screen Space with Camere.
It works on the editor.

**Comment by buihuuloc** [comment]
It happens after upgrading to the newest version

**Comment by mob-sakai** [comment]
What version did you use before?

**Comment by buihuuloc** [comment]
It seems a very old one.
I don't remember exactly.

**Comment by buihuuloc** [comment]
I added SpriteGlow package in my project

**Comment by mob-sakai** [comment]
Hmm, I see.

**Comment by buihuuloc** [comment]
I checked my project.
I am using version v2.6.1.
It is a very old one

**Comment by buihuuloc** [comment]
I've just updated to v2.8.3 and It works now.

How can I upgrade from version v2.x to version v3.x?

Thanks, 
Loc

**Comment by mob-sakai** [comment]
That information is very important!
Thank you!

**Comment by AbrahamArmasCordero** [comment]
so in what version is this solved?, i have a problem that the blur doesn't work in the build but does in the editor, im troubleshooting it right know version 3.0.1.
By doesnt work i mean that when i click the button it makes darker the screen but doesnt blur, also dark color is not normal as i putted multiply by white

**Comment by mob-sakai** [comment]
Hi @AbrahamArmasCordero 
Can you submit a screenshot and a minimum project that reproduce the issue?
They help to solve the issue.

**Comment by mob-sakai** [comment]
If you use "Immediate Capturing" option, disable it.
It doesn't work on some devices and will be removed next version.
![](https://user-images.githubusercontent.com/12690315/54873178-67d78200-4e14-11e9-8af6-eb0a9658b827.png)

**Comment by AbrahamArmasCordero** [comment]
Im testing 3.1.0, if it happens again i'll publish a custom issue for this with all the details i can provide :D. i was in 3.0.1 2018.3.2f1 LWRP Setup and not Immediate Capturing activated :D, i also had installed old version of TMP UIEffects bad setup so i'm making everything again let's see if that works 💃

**Comment by boloyo** [comment]
Capture twice in the same frame may reproduce the problem.

**Comment by mob-sakai** [comment]
@boloyo 
Thank you for reporting.
I would like to know more information.

* Unity version
* UIEffect version
* Platforms
* Others

**Comment by boloyo** [comment]
> @boloyo
> Thank you for reporting.
> I would like to know more information.
> 
> * Unity version
> * UIEffect version
> * Platforms
> * Others

UIEffect v3.0.2, using Unity 2017/2018 build and run on latest iOS with Immediate Capturing off , this problem never happened on Editor.

**Comment by mob-sakai** [comment]
@boloyo 
Can you submit a reproducible minimum project for this issue?
It helps to solve the issue.

**Comment by boloyo** [comment]
> @boloyo
> Can you submit a reproducible minimum project for this issue?
> It helps to solve the issue.

Just add Capture(); after the Capture(); in UIEffectCapuredImages.cs at line 219, then run the demo on iOS device, click "open dialog".

**Comment by mob-sakai** [comment]
Thanks!
I will try it later! 😄

**Comment by boloyo** [comment]
> Thanks!
> I will try it later! 😄

I created a bugfix pull request for the bug, just for reference.
